### PR TITLE
Docker Image

### PR DESCRIPTION
**Pull request by NathanTheGr8**
#72 This adds a docker file and instructions to the readme. Its pretty simple. If the request gets merged I @mescon should make his own image on docker hub and change the instructions to pull from that new repo.

### CODE REVIEW

**Comment by mescon** [comment]
Hey, thanks for the pull request!

Is there any particular reason that I should be having the docker hub image? I don't use Docker myself and I wouldn't know the first thing about how to run it - besides, I'm just glad if you'd be willing to help out and keep it updated for those who prefer Docker.
Thoughts?

**Comment by NathanTheGr8** [comment]
This is a pretty simple web app with not a lot of complicated setup or dependancies. Docker's advantage is isolating the app and handling all that for you. You just have to run a simple one liner and it is setup. For this app the end user doesn't have to worry about setting up a web server or port conflicts with an existing page. The just specify the port they want when they run the setup. 

I would be glad to help keep the docker image updated. The advantage of having the image linked to this Github repo is that it will do a new build every time something is pushed to master. The image itself would only have to be changed if the instructions on how to set it up changed. IE we need a newer version of php installed on the host or we need to change where the files are stored on the server. It really shouldn't require much change.

**Comment by CoreyJ87** [comment]
This is great. I love using docker these days. I'm using it at work now for ALOT of our apps and whatnot. Thanks for taking the time to make the dockerfile @NathanTheGr8

**Comment by mescon** [comment]
Hey, I did it - would you mind trying it out? I linked Github with https://hub.docker.com/r/mescon/muximux/

**Comment by mescon** [comment]
Btw, I saw some guys did this: https://github.com/linuxserver/docker-muximux - is that a better approach than we are doing? Apache uses more memory, no? Also, they have auto-update on startup... our approach just builds a new image for every push we do right? Does that mean the use needs to re-download the image to get the latest version?

**Comment by NathanTheGr8** [comment]
1. In the instructions change it from docker pull mescon/Muximux to docker pull mescon/muximux. 

2. lol no I didn't find theirs. That one is better because it mounts the config from the host. so if you destroy the container and make another one you won't have to reset it up. Its config will be mapped from the host. 
The PGID and PUID are not important for this application really. It would be for something like couch potato or sab etc where the docker container is working with files that are on the host. That insures that they have proper rights to those files. The Timezone parameter I have no idea if it is useful. I have seen people specify it, but don't see how it is useful.

We can modify our dockerfile and instructions so the config is mounted from the host.

**Comment by mescon** [comment]
Shouldn't we just link their dockerfile or copy it straight up, in case they close down or do massive changes we don't like? I'd be happy to see a pull request, as Docker is a bit outside of my comfort zone :-)

**Comment by NathanTheGr8** [comment]
Does anyone know what this part does?

# Adding Custom files
ADD defaults/ /defaults/
ADD init/ /etc/my_init.d/
RUN chmod -v +x /etc/service/*/run && chmod -v +x /etc/my_init.d/*.sh

it seems like it as adding a service to run at start up but I am not sure what would need to be. It is just a static web page.

**Comment by NathanTheGr8** [comment]
nvm I figured that out. I didn't look around their repo and see their init and defaults folder. derp

**Comment by NathanTheGr8** [comment]
@mescon The linuxserver docker image doesn't work it appears. It fails out when it is trying to modify the permissions of a file. This seems to be some sort of long running [issue](https://github.com/docker/docker/issues/6047) with docker. It seems like it was solved?, but I don't really understand the thread.
```
*** Running /etc/my_init.d/40_copy_config.sh...
chown: changing ownership of ‘/config/www/muximux/.git/objects/pack/pack-75a8cd6854f76c54f2db5720361e91b56704e310.idx’: Permission denied
chown: changing ownership of ‘/config/www/muximux/.git/objects/pack/pack-75a8cd6854f76c54f2db5720361e91b56704e310.pack’: Permission denied
*** /etc/my_init.d/40_copy_config.sh failed with status 1
2016-08-22T20:03:57.345429834Z 
*** Killing all processes...
```

I was working on my own docker file that incorporated the config as a mounted volume and sym linked to the root of the web directory. However I am running in to a problem. The image builds fine  but the sym link doesn't seem to exist when I go to check. I am guessing that somewhere in your muximux.php code you are moving the settings.ini.php-example file to settings.ini.php when the app starts up. This is overriding my sym linked one.

**Pull request merged**
