### PR TITLE
Docker Image

### PR DESCRIPTION
**Pull request by NathanTheGr8**
#72 
@mescon The [linuxserver](https://github.com/linuxserver/docker-muximux) docker image doesn't work. It fails out when it is trying to modify the permissions of a file. This seems to be some sort of long running [issue](https://github.com/docker/docker/issues/6047) with docker. It seems like it was solved?, but I don't really understand the thread.
```
*** Running /etc/my_init.d/40_copy_config.sh...
chown: changing ownership of ‘/config/www/muximux/.git/objects/pack/pack-75a8cd6854f76c54f2db5720361e91b56704e310.idx’: Permission denied
chown: changing ownership of ‘/config/www/muximux/.git/objects/pack/pack-75a8cd6854f76c54f2db5720361e91b56704e310.pack’: Permission denied
*** /etc/my_init.d/40_copy_config.sh failed with status 1
2016-08-22T20:03:57.345429834Z 
*** Killing all processes...
```
I was working on my own docker file that incorporated the config as a mounted volume and sym linked to the root of the web directory. However I am running in to a problem. The image builds fine but the sym link doesn't seem to exist when I go to check. It looks like in your muximux.php write_ini() function you are saving over the existing file. I am not sure how to change this to preserver the symlink.

### CODE REVIEW

**Comment by mescon** [comment]
Could you please submit pull requests to the develop branch instead?

**Comment by NathanTheGr8** [comment]
switched

**Comment by mescon** [comment]
Thanks! Have you tested the dockerfile? I'll push to master now and see if Docker Hub rebuilds it.

**Comment by NathanTheGr8** [comment]
yeah I have tested it. It builds fine. Your config file on the host is mapped to the container at /config/filename. However the sym link from /config to /var/www/html ether doesn't get applied (I don't think so, no errors in build log) or it gets overridden when the app "launches".

**Pull request merged**
